In [1]:
from pandas import Series,DataFrame
import pandas as pd
import numpy as np

df1 = DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})
df2 = DataFrame({'key':['a','b','d'],'data2':range(3)})
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [2]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [3]:
pd.merge(df1,df2)#注意，并没指明要用哪一个列进行连接，如果没有指定，merge就会将重叠列的列名当做健

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [4]:
pd.merge(df1,df2,on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [5]:
df3 = DataFrame({'lkey':['b','b','a','c','a','a','b'],'data1':range(7)})
df4 = DataFrame({'rkey':['a','b','d'],'data2':range(3)})
pd.merge(df3,df4,left_on='lkey',right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [6]:
pd.merge(df1,df2,how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [7]:
df1 = DataFrame({'key':['b','b','a','c','a','a','b'],'data1':range(7)})
df2 = DataFrame({'key':['a','b','d','a'],'data2':range(4)})
pd.merge(df1,df2,on='key',how='left')

data1 key  data2
0      0   b    1.0
1      1   b    1.0
2      2   a    0.0
3      2   a    3.0
4      3   c    NaN
5      4   a    0.0
6      4   a    3.0
7      5   a    0.0
8      5   a    3.0
9      6   b    1.0

In [8]:
left = DataFrame({'key1':['foo','foo','bar'],
                  'key2':['one','two','one'],
                  'lval':[1,2,3]})
right = DataFrame({'key1':['foo','foo','bar','bar'],
                   'key2':['one','one','one','two'],
                   'rval':[4,5,6,7]})
pd.merge(left,right,on=['key1','key2'],how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [9]:
pd.merge(left,right,on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [10]:
pd.merge(left,right,on='key1',suffixes=('_left','_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [11]:
left1 = DataFrame({'key':['a','b','a','a','b','c'],'value':range(6)})
right1 = DataFrame({'group_val':[3.5,7]},index=['a','b'])
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [12]:
right1

group_val
a        3.5
b        7.0

In [13]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [14]:
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [15]:
left = DataFrame({'key1':['Ohio','Ohio','Ohio','Nevada','Nevada'],
                  'key2':[2000,2001,2002,2001,2002],
                  'data':np.arange(5.)})
right = DataFrame(np.arange(12).reshape((6,2)),
                  index=[['Nevada','Nevada','Ohio','Ohio','Ohio','Ohio'],[2001,2000,2000,2000,2001,2002]],
                 columns=['event1','event2'])
left

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [16]:
right

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [17]:
pd.merge(left,right,left_on=['key1','key2'],right_index=True)

data    key1  key2  event1  event2
0   0.0    Ohio  2000       4       5
0   0.0    Ohio  2000       6       7
1   1.0    Ohio  2001       8       9
2   2.0    Ohio  2002      10      11
3   3.0  Nevada  2001       0       1

In [18]:
pd.merge(left,right,left_on=['key1','key2'],right_index=True,how='outer')

data    key1  key2  event1  event2
0   0.0    Ohio  2000     4.0     5.0
0   0.0    Ohio  2000     6.0     7.0
1   1.0    Ohio  2001     8.0     9.0
2   2.0    Ohio  2002    10.0    11.0
3   3.0  Nevada  2001     0.0     1.0
4   4.0  Nevada  2002     NaN     NaN
4   NaN  Nevada  2000     2.0     3.0

In [19]:
left2 = DataFrame([[1.,2.],[3.,4.],[4.,6.]],index=['a','c','e'],columns=['Ohio','Nevada'])
right2 = DataFrame([[7.,8.],[9.,10.],[11.,12.],[13,14]],index=['b','c','d','e'],columns=['Missouri','Alabama'])
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   4.0     6.0

In [20]:
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [21]:
pd.merge(left2,right2,how='outer',left_index=True,right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   4.0     6.0      13.0     14.0

In [22]:
left2.join(right2,how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   4.0     6.0      13.0     14.0

In [23]:
left1.join(right1,on='key')

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [24]:
another = DataFrame([[1.,8.],[9.,10.],[11.,12.],[16.,17.]],index=['a','c','e','f'],columns=['New York','Oregon'])
left2.join([right2,another])

Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       1.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   4.0     6.0      13.0     14.0      11.0    12.0

In [25]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [27]:
s1 = Series([0,1],index=['a','b'])
s2 = Series([2,3,4],index=['c','d','e'])
s3 = Series([5,6],index=['f','g'])
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [28]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [29]:
s4 = pd.concat([s1*5,s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [30]:
pd.concat([s1,s4],axis=1)

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [31]:
pd.concat([s1,s4],axis=1,join='inner')

0  1
a  0  0
b  1  5

In [32]:
pd.concat([s1,s4],axis=1,join_axes=[['a','c','b','e']])


0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [33]:
result = pd.concat([s1,s1,s4],keys=['one','two','three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  a    0
       b    5
       f    5
       g    6
dtype: int64

In [34]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  0.0  5.0  5.0  6.0

In [35]:
pd.concat([s1,s1,s4],axis=1,keys=['one','two','three'])

one  two  three
a  0.0  0.0      0
b  1.0  1.0      5
f  NaN  NaN      5
g  NaN  NaN      6

In [36]:
df1 = DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],columns=['one','two'])
df2 = DataFrame(5+np.arange(4).reshape(2,2),index=['a','c'],columns=['three','four'])
t = pd.concat([df1,df2],axis=1,keys=['level1','level2'])

In [37]:
t

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [38]:
t['level1']

one  two
a    0    1
b    2    3
c    4    5

In [39]:
t2 = pd.concat([df1,df2],axis=1,keys=['level1','level2'],names=['upper','lower'])

In [40]:
t2

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [41]:
t2['upper']

KeyError: 'upper'

In [ ]:
df1 = DataFrame(np.random.randn(3,4),columns=['a','b','c','d'])
df2 = DataFrame(np.random.randn(2,3),columns=['b','d','a'])
df1

In [ ]:
df2

In [ ]:
pd.concat([df1,df2],ignore_index=True)

In [ ]:
a = Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index=['f','e','d','c','b','a'])
b = Series(np.arange(len(a),dtype=np.float64),index=['f','e','d','c','b','a'])
a

In [ ]:
b

In [ ]:
b[-1] = np.nan

In [ ]:
b

In [ ]:
np.where(pd.isnull(a),b,a)

In [ ]:
b[:-2]

In [ ]:
a[2:]

In [ ]:
b[:-2].combine_first(a[2:])

In [ ]:
df1 = DataFrame({'a':[1.,np.nan,5.,np.nan],
                 'b':[np.nan,2.,np.nan,6.],
                 'c':range(2,18,4)})
df2 = DataFrame({'a':[5.,4.,np.nan,3.,7.],
                 'b':[np.nan,3.,4.,6.,8.]})
df1

In [ ]:
df2

In [ ]:
df1.combine_first(df2)

In [ ]:
data = DataFrame(np.arange(6).reshape((2,3)),index=pd.Index(['Ohio','Colorado'],name='state'),columns=pd.Index(['one','two','three'],name='number'))
data

In [ ]:
result = data.stack()
result

In [ ]:
result.unstack()

In [ ]:
result.unstack(0)

In [ ]:
result.unstack('state')

In [ ]:
s1 = Series([0,1,2,3],index=['a','b','c','d'])
s2 = Series([4,5,6],index=['c','d','e'])
data2 = pd.concat([s1,s2],keys=['one','two'])

In [ ]:
data2

In [ ]:
data2.unstack()

In [ ]:
data2.unstack().stack()

In [ ]:
data2.unstack().stack(dropna=False)

In [ ]:
result

In [ ]:
df = DataFrame({'left':result,'right':result+5},columns=pd.Index(['left','right'],name='side'))
df

In [ ]:
df.unstack('state')

In [ ]:
df.unstack('state').stack('side')

In [42]:
ldata = pd.read_csv('ch07/macrodata.csv')
ldata[:10]

year  quarter   realgdp  realcons  realinv  realgovt  realdpi    cpi  \
0  1959.0      1.0  2710.349    1707.4  286.898   470.045   1886.9  28.98   
1  1959.0      2.0  2778.801    1733.7  310.859   481.301   1919.7  29.15   
2  1959.0      3.0  2775.488    1751.8  289.226   491.260   1916.4  29.35   
3  1959.0      4.0  2785.204    1753.7  299.356   484.052   1931.3  29.37   
4  1960.0      1.0  2847.699    1770.5  331.722   462.199   1955.5  29.54   
5  1960.0      2.0  2834.390    1792.9  298.152   460.400   1966.1  29.55   
6  1960.0      3.0  2839.022    1785.8  296.375   474.676   1967.8  29.75   
7  1960.0      4.0  2802.616    1788.2  259.764   476.434   1966.6  29.84   
8  1961.0      1.0  2819.264    1787.7  266.405   475.854   1984.5  29.81   
9  1961.0      2.0  2872.005    1814.3  286.246   480.328   2014.4  29.92   

      m1  tbilrate  unemp      pop  infl  realint  
0  139.7      2.82    5.8  177.146  0.00     0.00  
1  141.7      3.08    5.1  177.830  2.34     0.74  
2  140.5      3.82    5.3  178.657  2.74     1.09  
3  140.0      4.33    5.6  179.386  0.27     4.06  
4  139.6      3.50    5.2  180.007  2.31     1.19  
5  140.2      2.68    5.2  180.671  0.14     2.55  
6  140.9      2.36    5.6  181.528  2.70    -0.34  
7  141.1      2.29    6.3  182.287  1.21     1.08  
8  142.1      2.37    6.8  182.992 -0.40     2.77  
9  142.9      2.29    7.0  183.691  1.47     0.81

In [43]:
pivoted = ldata[:100].pivot('year','quarter','pop')
pivoted

quarter      1.0      2.0      3.0      4.0
year                                       
1959.0   177.146  177.830  178.657  179.386
1960.0   180.007  180.671  181.528  182.287
1961.0   182.992  183.691  184.524  185.242
1962.0   185.874  186.538  187.323  188.013
1963.0   188.580  189.242  190.028  190.668
1964.0   191.245  191.889  192.631  193.223
1965.0   193.709  194.303  194.997  195.539
1966.0   195.999  196.560  197.207  197.736
1967.0   198.206  198.712  199.311  199.808
1968.0   200.208  200.706  201.290  201.760
1969.0   202.161  202.677  203.302  203.849
1970.0   204.401  205.052  205.788  206.466
1971.0   207.065  207.661  208.345  208.917
1972.0   209.386  209.896  210.479  210.985
1973.0   211.420  211.909  212.475  212.932
1974.0   213.361  213.854  214.451  214.931
1975.0   215.353  215.973  216.587  217.095
1976.0   217.528  218.035  218.644  219.179
1977.0   219.684  220.239  220.904  221.477
1978.0   221.991  222.585  223.271  223.865
1979.0   224.438  225.055  225.801  226.451
1980.0   227.061  227.726  228.417  228.937
1981.0   229.403  229.966  230.641  231.157
1982.0   231.645  232.188  232.816  233.322
1983.0   233.781  234.307  234.907  235.385

In [44]:
pivoted.head()

quarter      1.0      2.0      3.0      4.0
year                                       
1959.0   177.146  177.830  178.657  179.386
1960.0   180.007  180.671  181.528  182.287
1961.0   182.992  183.691  184.524  185.242
1962.0   185.874  186.538  187.323  188.013
1963.0   188.580  189.242  190.028  190.668

In [45]:
ldata['value2'] = np.random.randn(len(ldata))
ldata[:10]

year  quarter   realgdp  realcons  realinv  realgovt  realdpi    cpi  \
0  1959.0      1.0  2710.349    1707.4  286.898   470.045   1886.9  28.98   
1  1959.0      2.0  2778.801    1733.7  310.859   481.301   1919.7  29.15   
2  1959.0      3.0  2775.488    1751.8  289.226   491.260   1916.4  29.35   
3  1959.0      4.0  2785.204    1753.7  299.356   484.052   1931.3  29.37   
4  1960.0      1.0  2847.699    1770.5  331.722   462.199   1955.5  29.54   
5  1960.0      2.0  2834.390    1792.9  298.152   460.400   1966.1  29.55   
6  1960.0      3.0  2839.022    1785.8  296.375   474.676   1967.8  29.75   
7  1960.0      4.0  2802.616    1788.2  259.764   476.434   1966.6  29.84   
8  1961.0      1.0  2819.264    1787.7  266.405   475.854   1984.5  29.81   
9  1961.0      2.0  2872.005    1814.3  286.246   480.328   2014.4  29.92   

      m1  tbilrate  unemp      pop  infl  realint    value2  
0  139.7      2.82    5.8  177.146  0.00     0.00 -2.007894  
1  141.7      3.08    5.1  177.830  2.34     0.74  0.137186  
2  140.5      3.82    5.3  178.657  2.74     1.09 -0.313377  
3  140.0      4.33    5.6  179.386  0.27     4.06  1.605280  
4  139.6      3.50    5.2  180.007  2.31     1.19 -0.164140  
5  140.2      2.68    5.2  180.671  0.14     2.55  2.095980  
6  140.9      2.36    5.6  181.528  2.70    -0.34  0.573319  
7  141.1      2.29    6.3  182.287  1.21     1.08 -0.020051  
8  142.1      2.37    6.8  182.992 -0.40     2.77 -0.458799  
9  142.9      2.29    7.0  183.691  1.47     0.81 -0.688743

In [46]:
data = DataFrame({'k1':['one']*3+['two']*4,
                 'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [47]:
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [48]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [49]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [50]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
3  two   3   3

In [51]:
data.drop_duplicates(['k1','k2'])

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [52]:
data = DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','hony ham','nova lox'],
                 'ounces':[4,3,12,6,7.5,8,3,5,6]
                 })
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7     hony ham     5.0
8     nova lox     6.0

In [53]:
meat_to_animal ={'bacon':'pig','pulled pork':'pig','pastami':'cow','corned beef':'cow','honey ham':'pig','nova lox':'salmon'}
meat_to_animal

{'bacon': 'pig',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon',
 'pastami': 'cow',
 'pulled pork': 'pig'}

In [54]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     NaN
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     NaN
7     hony ham     5.0     NaN
8     nova lox     6.0  salmon

In [55]:
data['food'].map(lamba x:meat_to_animal[x.lower()])

SyntaxError: invalid syntax (<ipython-input-55-2b6ba3926891>, line 1)

In [56]:
data = Series([1.,-999.,2.,-999.,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [58]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [59]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [60]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [61]:
data = DataFrame(np.arange(12).reshape((3,4)),index=['Ohio','Colorado','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [62]:
data.index.map(str.upper)

Index(['OHIO', 'COLORADO', 'NEW YORK'], dtype='object')

In [63]:
data.index = data.index.map(str.upper)

In [64]:
data

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [65]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [66]:
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [67]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins=[18,25,35,60,100]
cats = pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [68]:
cats.labels

d:\www\learn-python\venv\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 'labels' is deprecated. Use 'codes' instead
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [69]:
cats.levels

AttributeError: 'Categorical' object has no attribute 'levels'

In [70]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [142]:
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [143]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [144]:
data = np.random.rand(20)
data

array([ 0.29113723,  0.22918744,  0.46322111,  0.66422842,  0.36162359,
        0.53272413,  0.62526469,  0.27545974,  0.32918069,  0.99506614,
        0.63412378,  0.49678481,  0.93130041,  0.38794578,  0.98854075,
        0.49933569,  0.81069977,  0.79339851,  0.16296667,  0.31925367])

In [145]:
pd.cut(data,4,precision=2)

[(0.16, 0.37], (0.16, 0.37], (0.37, 0.58], (0.58, 0.79], (0.16, 0.37], ..., (0.37, 0.58], (0.79, 1.0], (0.79, 1.0], (0.16, 0.37], (0.16, 0.37]]
Length: 20
Categories (4, interval[float64]): [(0.16, 0.37] < (0.37, 0.58] < (0.58, 0.79] < (0.79, 1.0]]

In [71]:
np.random.seed(12345)

In [72]:
data = DataFrame(np.random.randn(1000,4))

In [73]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [74]:
col = data[3]
col[np.abs(col)>3]

97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [75]:
data[(np.abs(col)>3).any(1)]

ValueError: No axis named 1 for object type <class 'pandas.core.series.Series'>

In [76]:
data[np.abs(data)>3] = np.sign(data)*3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

In [78]:
np.sign(data)

0    1    2    3
0   -1.0  1.0 -1.0 -1.0
1    1.0  1.0  1.0  1.0
2    1.0  1.0  1.0 -1.0
3    1.0  1.0  1.0  1.0
4   -1.0 -1.0  1.0 -1.0
5   -1.0  1.0  1.0 -1.0
6   -1.0  1.0  1.0  1.0
7    1.0  1.0 -1.0 -1.0
8   -1.0 -1.0 -1.0  1.0
9   -1.0  1.0 -1.0  1.0
10  -1.0 -1.0 -1.0 -1.0
11  -1.0  1.0  1.0 -1.0
12   1.0  1.0  1.0  1.0
13  -1.0  1.0  1.0 -1.0
14  -1.0  1.0  1.0 -1.0
15   1.0 -1.0  1.0  1.0
16   1.0 -1.0 -1.0 -1.0
17  -1.0 -1.0 -1.0  1.0
18   1.0  1.0  1.0 -1.0
19  -1.0 -1.0 -1.0  1.0
20   1.0 -1.0  1.0  1.0
21   1.0  1.0 -1.0  1.0
22  -1.0  1.0  1.0  1.0
23  -1.0  1.0  1.0  1.0
24   1.0 -1.0  1.0  1.0
25  -1.0 -1.0 -1.0 -1.0
26  -1.0 -1.0  1.0  1.0
27  -1.0  1.0 -1.0  1.0
28   1.0 -1.0 -1.0 -1.0
29   1.0 -1.0  1.0 -1.0
..   ...  ...  ...  ...
970  1.0  1.0  1.0 -1.0
971 -1.0 -1.0 -1.0  1.0
972  1.0  1.0 -1.0 -1.0
973 -1.0  1.0  1.0 -1.0
974 -1.0 -1.0  1.0 -1.0
975 -1.0 -1.0  1.0 -1.0
976  1.0  1.0  1.0  1.0
977 -1.0  1.0  1.0  1.0
978  1.0 -1.0  1.0  1.0
979  1.0  1.0 -1.0  1.0
980 -1.0 -1.0 -1.0 -1.0
981 -1.0  1.0  1.0  1.0
982 -1.0  1.0  1.0  1.0
983 -1.0  1.0  1.0  1.0
984  1.0 -1.0  1.0 -1.0
985 -1.0  1.0  1.0  1.0
986 -1.0 -1.0  1.0 -1.0
987 -1.0 -1.0  1.0 -1.0
988 -1.0  1.0 -1.0 -1.0
989  1.0  1.0  1.0  1.0
990 -1.0 -1.0 -1.0  1.0
991  1.0 -1.0  1.0  1.0
992 -1.0  1.0 -1.0 -1.0
993  1.0  1.0 -1.0  1.0
994  1.0 -1.0  1.0  1.0
995  1.0  1.0 -1.0  1.0
996 -1.0 -1.0 -1.0 -1.0
997 -1.0  1.0  1.0  1.0
998 -1.0 -1.0 -1.0 -1.0
999  1.0  1.0  1.0  1.0

[1000 rows x 4 columns]

In [79]:
df = DataFrame(np.arange(5*4).reshape(5,4))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [80]:
sampler = np.random.permutation(5)
sampler

array([1, 0, 2, 3, 4])

In [81]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [83]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19

In [88]:
np.random.permutation(len(df))[:3]

array([1, 4, 0])

In [90]:
bag = np.array([5,7,-1,6,4])
sampler = np.random.randint(0,len(bag),size=10)
sampler

array([1, 1, 2, 3, 0, 1, 2, 2, 3, 2])

In [91]:
draws = bag.take(sampler)
draws

array([ 7,  7, -1,  6,  5,  7, -1, -1,  6, -1])

In [92]:
df = DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [94]:
dummies = pd.get_dummies(df['key'],prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [96]:
df['data1']

0    0
1    1
2    2
3    3
4    4
5    5
Name: data1, dtype: int64

In [97]:
df[['data1']]

data1
0      0
1      1
2      2
3      3
4      4
5      5

In [99]:
mnames = ['movie_id','title','genres']
movies = pd.read_table('ch02/movielens/movies.dat',sep='::',header=None,names=mnames)
movies[:10]

d:\www\learn-python\venv\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [100]:
genre_iter = (set(x.split('|')) for x in movies.genres)
genre_iter

<generator object <genexpr> at 0x00000000056AB8E0>

In [101]:
genres = sorted(set.union(*genre_iter))
genres

['Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [106]:
dummies = DataFrame(np.zeros((len(movies),len(genres))),columns=genres)
for i,gen in enumerate(movies.genres)
    dummies.ix[i,gen.split('|')] = 1

movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.ix[0]

SyntaxError: invalid syntax (<ipython-input-106-9f06824894eb>, line 2)

In [107]:
values = np.random.rand(10)
values

array([ 0.23784062,  0.85564381,  0.58743194,  0.15314009,  0.5950288 ,
        0.38508854,  0.44740483,  0.32410284,  0.92360521,  0.51923163])

In [108]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           1           0           0           0
1           0           0           0           0           1
2           0           0           1           0           0
3           1           0           0           0           0
4           0           0           1           0           0
5           0           1           0           0           0
6           0           0           1           0           0
7           0           1           0           0           0
8           0           0           0           0           1
9           0           0           1           0           0